FROM debian:12
RUN apt -y update && apt -y install --no-install-recommends git python3 python3-pip espeak-ng cmake ninja-build
RUN git clone https://github.com/nerdaxic/glados-tts.git /glados-tts
RUN pip install --break-system-packages --no-cache-dir flask wheel numpy phonemizer inflect unidecode scipy
RUN apt -y install --no-install-recommends python3-torch
RUN mkdir /glados-tts/audio
WORKDIR /glados-tts
ENTRYPOINT [ "/usr/bin/python3", "engine.py"]